"""create cleanings table

Revision ID: 01de5d6d6fe2
Revises: d0a8c1d2f974
Create Date: 2021-03-11 14:23:51.587458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01de5d6d6fe2'
down_revision = 'd0a8c1d2f974'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cleanings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('cleaning_type',sa.String, nullable=True), #Added by me
    sa.Column('price', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cleanings')
    # ### end Alembic commands ###
