"""First migration

Revision ID: 217b0297645e
Revises: 
Create Date: 2021-03-11 00:00:54.703367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '217b0297645e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
