"""users create  table

Revision ID: 332615f6a5de
Revises: 7eeda0b50271
Create Date: 2021-03-12 08:17:56.729542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '332615f6a5de'
down_revision = '7eeda0b50271'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
