"""users create  table

Revision ID: 7eeda0b50271
Revises: cd8d71f31785
Create Date: 2021-03-12 08:17:10.174018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7eeda0b50271'
down_revision = 'cd8d71f31785'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
