"""create cleanings table

Revision ID: 9a3c4bbc4a10
Revises: 01de5d6d6fe2
Create Date: 2021-03-11 14:44:49.382481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a3c4bbc4a10'
down_revision = '01de5d6d6fe2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('timestampedbase')
    # ### end Alembic commands ###
