"""remove use of enum

Revision ID: cf71dac8d46a
Revises: 9a3c4bbc4a10
Create Date: 2021-03-11 14:45:59.321021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf71dac8d46a'
down_revision = '9a3c4bbc4a10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
