"""create cleanings table

Revision ID: d0a8c1d2f974
Revises: 2834cde76a5a
Create Date: 2021-03-11 14:19:08.170260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0a8c1d2f974'
down_revision = '2834cde76a5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
